---
# tasks file for abyres.hdp-pgsql
- name: install postgresql
  yum: name=postgresql-server,postgresql,python-psycopg2 state=latest

- name: create hive metastore db
  postgresql_db: name=hive_metastore encoding='UTF-8'
  become: true
  become_user: postgres

- name: create hive metastore user
  postgresql_user: db=hive_metastore name=hive password={{ hive_db_password }} priv=ALL
  become: true
  become_user: postgres

- name: create oozie db
  postgresql_db: name=oozie encoding='UTF-8'
  become: true
  become_user: postgres

- name: create hive metastore user
  postgresql_user: db=hive_metastore name=oozie password={{ oozie_db_password }} priv=ALL
  become: true
  become_user: postgres
