---
# tasks file for abyres.ntpd
#
- name: install ntp
  yum: name=ntp,ntpdate state=latest

- name: configure ntp 
  template: src=ntp.conf_tmpl dest=/etc/ntp.conf mode=0644

- name: start ntp service
  service: name=ntpd state=started enabled=yes
